# Generated by Django 4.0.10 on 2023-10-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blog_likes_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
