# Generated by Django 4.0.10 on 2023-10-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_like_alter_blog_likes_delete_likes_like_blog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
